SELECT ?lymphocyte ?segmentation WHERE {
    ?stroma histo:hasCell ?lymphocyte .
    ?lymphocyte rdf:type histo:StromaCell ;
        histo:segmentation ?segmentation ;
        histo:entityReference ?lymphocyteRef .
    ?lymphocyteRef rdf:type histo:CellReference ;
        histo:hasXref ?lymphocyteXRef .
    ?lymphocyteXRef rdf:type histo:UnificationXref ;
        histo:uri "http://purl.obolibrary.org/obo/FMA_62863" .
}
